# Generated by Django 4.2.7 on 2023-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi_app', '0002_weatherdata_delete_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('hygr', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
