# Generated by Django 4.2.7 on 2023-11-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi_app', '0003_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
